version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: LHN_v2_DB
    restart: always
    env_file: mariadb.env
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - ./database:/var/lib/mysql:rw
  mysql:
    image: mysql:latest
    container_name: LHN_old_DB
    restart: always
    env_file: mysql_old.env
    ports:
      - "3307:3307"
    networks:
      - my-network
    volumes:
      - ./database_old:/var/lib/mysql:rw
  node-vite:
    image: node:18
    container_name: LHN_v2_Vite
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "5173:5173" # Port de Vite
    command: sh -c "npm install && npm run watch"
    networks:
      - my-network
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: LHN_v2
    restart: always
    ports:
      - "666:80"
    depends_on:
      - mariadb
      - mysql
    networks:
      - my-network
    volumes:
      - ./src:/app:rw

networks:
  my-network:
    driver: bridge
